version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es01
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.cors.allow-origin=http://localhost:63342"
      - "http.cors.enabled=true"
      - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
      - "http.cors.allow-headers=Authorization, X-Requested-With,X-Auth-Token,Content-Type, Content-Length"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kib01
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    networks:
      - elastic
    depends_on:
      - elasticsearch


volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge


